# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
require:
  - rubocop-performance
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Metrics/ParameterLists:
  CountKeywordArgs: false

Layout/LineLength:
  Max: 82

Metrics/MethodLength:
  Max: 25

# We have a very specific naming convention
# that we must use for importers
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'lib/safety_alerts/alert_importer/*.rb'
    - 'lib/safety_alerts/geometry_importer/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/safety_alerts/alert_importer/*.rb'
    - 'lib/safety_alerts/geometry_importer/*.rb'

RSpec/FilePath:
  IgnoreMethods: true
  CustomTransform:
    US_NWS: us_nws
    AU_BOM: au_bom
    AU_NSW_RFS: au_nsw_rfs

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: false
